Repository greenpeace/planet4-base, pull requests merged in 2019-03, with the labels that each got.

#21 Feature/lint
  .circleci/config.yml
  .githooks/pre-commit
  .yamllint
  Makefile
  codeception.dist.yml
  composer-local.json
  composer.json
  tasks/pre-deploy/01-demo.sh
  tests/acceptance.suite.yml
  tests/composer.json
  tests/composer.lock
Labels: enhancement, qa

#23 PLANET-3266 remove searchwp
  composer.json
Labels: Review but don't merge

#25 Update connect2es
  tasks/post-deploy/02-connect2es.sh
Labels: Review and Merge

#26 PLANET-3303 - Add more tests for blocks with content creation
  tests/acceptance/ArticlesCreateCept.php
  tests/acceptance/CarouselCept.php
  tests/acceptance/CarouselHeaderCreateCept.php
  tests/acceptance/ColumnsIconsCreateCept.php
  tests/acceptance/ColumnsNoImageCreateCept.php
  tests/acceptance/ColumnsTasksCreateCept.php
  tests/acceptance/CoversCampaignCreateCept.php
  tests/acceptance/CoversContentCreateCept.php
  tests/acceptance/CoversTakeActionCreateCept.php
  tests/acceptance/Gallery3ColumnCreateCept.php
  tests/acceptance/GalleryGridCreateCept.php
  tests/acceptance/GallerySliderCreateCept.php
  tests/acceptance/SplitTwoColumnsCreateCept.php
  tests/acceptance/SubheaderCreateCept.php
  tests/acceptance/TakeActionBoxoutCreateCept.php
Labels: Review and Merge

#28 Check backend if comment was created
  tests/acceptance/AddCommentCept.php
Labels: Review and Merge
